/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputData {
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	double r;
};
typedef struct inputData inputData;

struct avgArray {
	double arr[2];
};
typedef struct avgArray avgArray;

struct productVector {
	struct {
		u_int vec_len;
		double *vec_val;
	} vec;
};
typedef struct productVector productVector;

#define MENU_PROG 0x23451111
#define MENU_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define INNERPRODUCT 1
extern  int * innerproduct_1(inputData *, CLIENT *);
extern  int * innerproduct_1_svc(inputData *, struct svc_req *);
#define AVERAGES 2
extern  avgArray * averages_1(inputData *, CLIENT *);
extern  avgArray * averages_1_svc(inputData *, struct svc_req *);
#define PRODUCT 3
extern  productVector * product_1(inputData *, CLIENT *);
extern  productVector * product_1_svc(inputData *, struct svc_req *);
extern int menu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INNERPRODUCT 1
extern  int * innerproduct_1();
extern  int * innerproduct_1_svc();
#define AVERAGES 2
extern  avgArray * averages_1();
extern  avgArray * averages_1_svc();
#define PRODUCT 3
extern  productVector * product_1();
extern  productVector * product_1_svc();
extern int menu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputData (XDR *, inputData*);
extern  bool_t xdr_avgArray (XDR *, avgArray*);
extern  bool_t xdr_productVector (XDR *, productVector*);

#else /* K&R C */
extern bool_t xdr_inputData ();
extern bool_t xdr_avgArray ();
extern bool_t xdr_productVector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
