/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdlib.h>

/*
 *  Η ρουτίνα "[1] Εσωτερικό γινόμενο των διανυσμάτων Χ * Υ"
 */
int* innerproduct_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
/*
 *  Υπολογισμός του εσωτερικού γινομένου Χ * Υ
 */	
	printf("[1] Inner product of X * Y\n");
	result = 0;
	for (i = 0; i < argp->X.X_len; i++)
		result = result + argp->X.X_val[i] * argp->Y.Y_val[i];
/*
 *  Εκτύπωση των αποτελεσμάτων του εσωτερικού γινομένου Χ * Υ
 */
	printf("\t---------------- Results -----------------\n");
	printf("\tX * Y : %d\n", result);
	printf("\tSending results to rpc client.\n");
/*
 *  Αποστολή των αποτελεσμάτων "[1] Εσωτερικό γινόμενο των διανυσμάτων Χ * Υ" στον rpc client
 */
	return &result;
}

/*
 *  Η ρουτίνα "[2] Μέση τιμή κάθε διανύσματος"
 */
avgArray* averages_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static avgArray  result;
	int i, sumX, sumY;
	double avgX, avgY;
/*
 *  Υπολογισμός του μέσου όρου των δύο διανυσμάτων Χ, Υ
 */
	printf("[2] Average value of each vector\n");
	sumX = 0;
	sumY = 0;
	for (i = 0; i < argp->X.X_len; i++)
		sumX += argp->X.X_val[i];
	for (i = 0; i < argp->Y.Y_len; i++)
		sumY += argp->Y.Y_val[i];
	avgX = sumX / argp->X.X_len;
	avgY = sumY / argp->Y.Y_len;
	result.arr[0] = avgX;
	result.arr[1] = avgY;
/*
 *  Εκτύπωση του μέσου όρου των δύο διανυσμάτων Χ, Υ
 */
	printf("\t---------------- Results -----------------\n");
	printf("\tAverage value of X : %lf\n", result.arr[0]);
	printf("\tAverage value of Y : %lf\n", result.arr[1]);
	printf("\tSending results to rpc client.\n");
/*
 *  Αποστολή των αποτελεσμάτων "[2] Μέση τιμή κάθε διανύσματος" στον rpc client
 */	
	return &result;
}

/*
 *  Η ρουτίνα "[3] Γινόμενο r * (X + Y)"
 */
productVector* product_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static productVector  result;
	int i;
/*
 *  Υπολογισμός του γινομένου r * (X + Y) και εκχώρηση σ' ένα νέο διάνυσμα
 */
	printf("[3] Product of r * (X + Y)\n");
	result.vec.vec_len = argp->X.X_len;
	result.vec.vec_val = (double *) malloc (result.vec.vec_len * sizeof(double));
	if (result.vec.vec_val == NULL)
	{
		fprintf(stderr, "Error on allocating memory.\n");
		exit(1);
	}
/*
 *	Εκτύπωση των περιεχομένων του διανύσματος r * (X + Y)
 */
	printf("\t---------------- Results -----------------\n");
	for (i = 0; i < result.vec.vec_len; i++) 
	{
		result.vec.vec_val[i] = argp->r * (argp->X.X_val[i] + argp->Y.Y_val[i]);
		printf("\tr * (X + Y)[%d] : %lf\n", i, result.vec.vec_val[i]);
	}
	printf("\tSending results to rpc client.\n");
/*
 *  Αποστολή των αποτελεσμάτων "[3] Γινόμενο r * (X + Y)" στον rpc client
 */
	return &result;
}
