/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_inputData (XDR *xdrs, inputData *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_avgArray (XDR *xdrs, avgArray *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 2,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_productVector (XDR *xdrs, productVector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vec.vec_val, (u_int *) &objp->vec.vec_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
