/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdlib.h>

/*
 *  Routine "[1] Inner product of vectors X * Y"
 */
int* innerproduct_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
/*
 *  Calculation of the inner product X * Y
 */	
	printf("[1] Inner product of X * Y\n");
	result = 0;
	for (i = 0; i < argp->X.X_len; i++)
		result = result + argp->X.X_val[i] * argp->Y.Y_val[i];
/*
 *  Print the results of the inner product X * Y
 */
	printf("\t---------------- Results -----------------\n");
	printf("\tX * Y : %d\n", result);
	printf("\tSending results to RPC client.\n");
/*
 *  Send the results "[1] Inner product of vectors X * Y" to the RPC client
 */
	return &result;
}

/*
 *  Routine "[2] Average value of each vector"
 */
avgArray* averages_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static avgArray  result;
	int i, sumX, sumY;
	double avgX, avgY;
/*
 *  Calculation of the average of the two vectors X, Y
 */
	printf("[2] Average value of each vector\n");
	sumX = 0;
	sumY = 0;
	for (i = 0; i < argp->X.X_len; i++)
		sumX += argp->X.X_val[i];
	for (i = 0; i < argp->Y.Y_len; i++)
		sumY += argp->Y.Y_val[i];
	avgX = sumX / argp->X.X_len;
	avgY = sumY / argp->Y.Y_len;
	result.arr[0] = avgX;
	result.arr[1] = avgY;
/*
 *  Print the average of the two vectors X, Y
 */
	printf("\t---------------- Results -----------------\n");
	printf("\tAverage value of X : %lf\n", result.arr[0]);
	printf("\tAverage value of Y : %lf\n", result.arr[1]);
	printf("\tSending results to RPC client.\n");
/*
 *  Send the results "[2] Average value of each vector" to the RPC client
 */	
	return &result;
}

/*
 *  Routine "[3] Product of r * (X + Y)"
 */
productVector* product_1_svc(inputData *argp, struct svc_req *rqstp)
{
	static productVector  result;
	int i;
/*
 *  Calculation of the product r * (X + Y) and storing it in a new vector
 */
	printf("[3] Product of r * (X + Y)\n");
	result.vec.vec_len = argp->X.X_len;
	result.vec.vec_val = (double *) malloc (result.vec.vec_len * sizeof(double));
	if (result.vec.vec_val == NULL)
	{
		fprintf(stderr, "Error on allocating memory.\n");
		exit(1);
	}
/*
 *  Print the contents of the vector r * (X + Y)
 */
	printf("\t---------------- Results -----------------\n");
	for (i = 0; i < result.vec.vec_len; i++) 
	{
		result.vec.vec_val[i] = argp->r * (argp->X.X_val[i] + argp->Y.Y_val[i]);
		printf("\tr * (X + Y)[%d] : %lf\n", i, result.vec.vec_val[i]);
	}
	printf("\tSending results to RPC client.\n");
/*
 *  Send the results "[3] Product of r * (X + Y)" to the RPC client
 */
	return &result;
}
